### ISSUE TITLE
sha3-bare workload software version

### ISSUE THREAD

**Issue by abejgonzalez** [ucb-bar/sha3-workload#2]
Would it be possible to add the following SW test to the repo: https://github.com/ucb-bar/sha3/blob/master/tests/sha3-sw-bm.c. It does the sha3 computation in software instead of through RoCC and would be a good example to compare against.

**Comment by abejgonzalez** [comment]
It would also have the tutorial attendees see the difference between an accelerated and non-accelerated version.

**Comment by a0u** [comment]
There's already [sha3-sw.c](../blob/master/benchmarks/src/sha3-sw.c).  Currently it doesn't compile in the bare-metal environment because of the assert, but that can be easily remedied.

What I did for the Duke tutorial is to print a cycle count.  The `*-bm` variants suppress the `printf`s, which can be conditionalized with the preprocessor, but I don't think that is necessary.  The prints don't significantly impact the simulation time in Verilator.

**Comment by abejgonzalez** [comment]
Sure. I just tried getting things to work on my end and I hit the `assert` error. If we could get it working, I think this would be great!

As for the cycle count, we can print the cycle count at the end to "prove" the difference between the two. I think that would be a good idea.
